spring:
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]': # 匹配所有请求
              allowedOrigins: "*" #跨域处理 允许所有的域
              allowedMethods: # 支持的方法
                - GET
                - POST
                - PUT
                - DELETE
      routes:
           #唯一标识
#            - id: blblog_qa_route
#            #路由跳转的URL
#              uri: http://localhost:8005
#              predicates:
#              #- Host=cloud.blblog.com**
#              - Path=/api/problem/**,/api/reply/**
#              filters:
#              #- PrefixPath=/problem,截取掉路径的第一节为真实路径
#              - StripPrefix=1
#              - name: RequestRateLimiter #请求数限流 名字不能随便写 ，使用默认的facatory
#                args:
#                  key-resolver: "#{@ipKeyResolver}"
#                  #希望允许用户每秒执行多少请求/令牌桶填充速率
#                  redis-rate-limiter.replenishRate: 1
#                  #用户在一秒钟内允许执行的最大请求数/令牌桶容量
#                  redis-rate-limiter.burstCapacity: 1
            #用户微服务
            - id: changgou_user_route
            #lb,负载均衡
              uri: lb://user
              predicates:
              #后面的不是属于user服务的后面再提出来
              - Path=/api/user/**,/api/article/**,/api/problem/**,/api/reply/**
              filters:
              - StripPrefix=1
  application:
    name: gateway
  #Redis配置
  redis:
    host: 192.168.211.132
    port: 6379
server:
  port: 8086
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka
  instance:
    prefer-ip-address: true
management:
  endpoint:
    gateway:
      enabled: true
    web:
      exposure:
        include: true